FROM redhat/ubi8:latest


ARG USER=auto_user
ARG UID=1000
ARG GID=100

ENV USER ${USER}
ENV HOME /home/${USER}

RUN yum -y update && \
    yum install -y python3 python3-pip openssh-server openssh sudo && \
    useradd -m -s /bin/bash -N -u $UID $USER && \
    echo "${USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers && \
    chmod 0440 /etc/sudoers && \
    chmod g+w /etc/passwd && \
    ssh-keygen -A 

COPY ssh_keys/id_rsa.pub $HOME/.ssh/authorized_keys 
RUN chown $USER:users -R $HOME/.ssh && \
    chmod 0755 $HOME/.ssh/authorized_keys

WORKDIR $HOME
USER ${UID}




EXPOSE 22
CMD ["sudo", "/usr/sbin/sshd", "-D"]