FROM redhat/ubi8:latest

ARG USER=auto_user
ARG UID=1000
ARG GID=100


RUN yum -y update && yum install -y sudo &&\
    yum install -y python3 python3-pip && \
    yum install -y vim openssh-clients iputils && \
    pip3 install --upgrade pip && \
    pip3 install ansible


ENV USER ${USER}
ENV HOME /home/${USER}

RUN useradd -m -s /bin/bash -N -u $UID $USER && \
    echo "${USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers && \
    chmod 0440 /etc/sudoers && \
    chmod g+w /etc/passwd 

COPY ssh_keys/ $HOME/.ssh/

RUN chown $USER:users -R $HOME/.ssh && \
    chmod 0755 $HOME/.ssh/id_rsa.pub && \
    chmod 0700 $HOME/.ssh/id_rsa

WORKDIR $HOME
USER ${UID}