FROM redhat/ubi8:latest


RUN yum -y update && \
    yum install -y python3 python3-pip && \
    yum install -y vim openssh-clients iputils && \
    pip3 install --upgrade pip && \
    pip3 install ansible
